### ISSUE TITLE
Share link returns 500 "This Edge Function has crashed."

### ISSUE THREAD

**Issue by marcoroth** [buttondown-email/share.bingo#1]
Hey there @jmduke, thanks for the awesome service!

I'm using Buttondown for my [Hotwire Weekly Newsletter](https://buttondown.email/hotwireweekly) and it seems like the share.bingo service crashes when trying to share the URL for it.

Specifically it's crashing on this URL:
https://share.bingo/email?url=https%3A%2F%2Fbuttondown.email%2Fhotwireweekly&text=I%20just%20subscribed%20to%20Hotwire%20Weekly!

A user reported this in an issue here:
https://github.com/marcoroth/hotwire.io/issues/35

Thank you!

**Comment by jmduke** [comment]
Thanks for the flag; will take a look at this this evening.

**Comment by jmduke** [comment]
Thanks for the flag; will take a look at this this evening.

**Comment by jmduke** [comment]
So this is basically a problem with Vercel's edge network. Compare prod vs. dev; Vercel is prepending a slash.

<img width="511" alt="image" src="https://github.com/buttondown-email/share.bingo/assets/461046/ca6f26a1-6dcb-4edb-b9ef-7896b9455e45">

This is pretty annoying, and afaict there's nothing we can do about it besides special casing `email` and having it not go through the edge network. I'll ship a fix in the morning.

**Comment by marcoroth** [comment]
Thanks for the update, Justin! 🙌🏼

**Comment by marcoroth** [comment]
Works great now, thanks Justin! 🙏🏼
